### ISSUE TITLE
Feature request: Summary email

### ISSUE THREAD

**Issue by mcshaz** [POPWorldMedia/POPForums#193]
It would be great if users could subscribe to a summary email - perhaps a choice between daily or weekly with the topic titles and the first 50 or so characters of recent activity in new threads or threads with recent comments.

**Comment by jeffputz** [comment]
Email as a notification mechanism is sliding to obscurity. Even the existing subscription mechanism is rarely used in my existing communities. Definitely will not implement this.

**Comment by mcshaz** [comment]
No worries

**Comment by mcshaz** [comment]
This is not a feature desired for PopForums - but I would like to follow up for the sake of anyone else using PopForums who would like this functionality.

I implemented this (in English only) in my fork of [PopForums.Sample](https://github.com/mcshaz/POPForums.Sample) (albeit with dependencies changed to the pre-release versions of PopForums hosted on GitHub at the time of posting, rather than the Nuget packages - these could be reinstalled).

The email templates are MS Outlook compatible, and generated from Razor .cshtml files.

The code is a long way from perfect (and probably reinvents the wheel in terms of accessing the database rather than using many of the pre-existing PopForums classes), but works effectively (used in production), and hopefully it is readable. 

As the functionality has been moved to separate projects (one for generating email templates from Razor & one for creating the emails), the only change to PopForums.Sample is the need to add to Startup.cs:

```C#
services.AddTransient<IRazorViewToStringRenderer, RazorViewToStringRenderer>();
services.AddCronJob<SendUpdateEmailCron>(c => {
	c.TimeZoneInfo = TimeZoneInfo.Local;
	c.CronExpression = "45 15 * * 2";
});
```
(the Cron expression means repeat mail-out beginning 15:45 every Tues)

Because the PopForums Database does not store the domain name, the (poorly named) SmtpSettings POCO has the current hack that users would need to change
```C#
        public bool IsHttpSsl { get { return true; } }
        public string DomainName { get { return "example.com";  } }
        // not bothering with Port for now
        //
```
Other than this it should be ready to go for anyone wishing to use it. 

Engaging users with updates on what is happening on the forum is, for me, a really important feature to keep users engaged & discussions moving.

**Comment by jeffputz** [comment]
A couple of things, for coaching purposes... you've got the Cronos dependency hidden away in another project, which is confusing.

Also, there's infrastructure for repeating jobs already, for the other background services that run when you use `services,AddPopForumsBackgroundServices()`. You derive from `ApplicationServiceBase` and register it in `BackgroundServices`. The reason for this is that it's then trivial to light up the same service in an Azure Function. It's not perfect, since the web-based code was written years before Azure existed. While a `BackgroundService` sets up a worker and wraps a single line of code, Azure functions do essentially the same thing, only cleaner since many are queue based. Compare [`UserSessionProcessor`](https://github.com/POPWorldMedia/POPForums/blob/master/src/PopForums.AzureKit.Functions/UserSessionProcessor.cs) to [`UserSessionWorker`](https://github.com/POPWorldMedia/POPForums/blob/master/src/PopForums/Services/UserSessionWorker.cs).

I would steer clear of the static methods and hard dependencies you have. They're harder to test.

Finally, the reason that there is no "domain name" setting is because it always bubbles up from the MVC layer. When a subscription email fires, for example, the MVC layer passes up functions to determine the link (see [`ForumController`](https://github.com/POPWorldMedia/POPForums/blob/5a672b8525d03d6022b883b8c19371e47a5c67e2/src/PopForums.Mvc/Areas/Forums/Controllers/ForumController.cs#L309)). `PostMasterService` doesn't care or know about how the links are generated, because it takes a delegate to figure it out.

All of that duplicate settings code is going to be hard to maintain if you try to stay in sync with the rest of the app as it chnages.

**Comment by mcshaz** [comment]
I missed that – thank you very much for the explanation – much appreciated.
