### ISSUE TITLE
Configuring error pages in dotnet causes duplicate claims identities

### ISSUE THREAD

**Issue by ed11s8c** [POPWorldMedia/POPForums#54]
I am getting a strange issue when configuring PopForums to have error pages. In a nutshell when I configure the site to reExecute a failed request to an error page, the logged in uses somehow has a second duplicate claim identity.

As mentioned the app is using claims authentication, and I have only ever seen this issue when executing `app.UseStatusCodePagesWithReExecute` from startup.cs. I am at a loss on how to debug this issue further.

I can see in the debug window the following:
```
HttpContext.User merged via AutomaticAuthentication from authenticationScheme
```

I don't know if this merging is somehow causing duplicate claims entries on the user.

**Full steps to reproduce the issue:**

* Clone [Popforums][1] master branch & setup with the default user (run and goto `/Forums/Setup`)
* Once setup login with the default user and try and access `/Forums/Setup` again. Now the database is active will throw and 403 Forbidden error.

* Replace `app.UseStatusCodePages();` with the following in `Startup.cs`: `app.UseStatusCodePagesWithReExecute("/Home");` which should move the user to an error page while preserving the error code (for simplicity rather than creating an error page just redirect to the homepage).
* Try and access `/Forums/Setup` and while in debug. The following exception is thrown[![enter image description here][2]][2]

Obviously the error is self is clear, the question is where the duplicate claims has come from. Any ideas @jeffputz ?

  [1]: https://github.com/POPWorldMedia/POPForums
  [2]: https://i.stack.imgur.com/XqQ1b.png

**Comment by jeffputz** [comment]
I'm not convinced that the error page is the problem, but remember that it is possible and by design that you can have multiple identities. What do you have configured in startup as far as identities go?

Also, setup can only be run once by design. The setup controller won't let you run it again if the database is setup. I think you realize that, but just saying.

**Comment by ed11s8c** [comment]
@jeffputz I understand that `Forums/Setup` can be only accessed once, I chose that page because I knew it would explicitly return and error code to test my error page routing.

As far as identities go, again I understand that multiple identities are possible however as it stands in your code, you use a `SingleOrDefault` in several places only assuming there is one. To further this, the second identity looks to be a duplicate of the PopForumsAuthScheme already on the user.

I have only touched one line in your solution to cause this problem.
`app.UseStatusCodePages();` => `app.UseStatusCodePagesWithReExecute("/Home");` within `Startup.cs`

**Comment by jeffputz** [comment]
There should only be one place, and it's selecting the identity by name:
https://github.com/POPWorldMedia/POPForums/blob/master/src/PopForums.Mvc/Areas/Forums/Authorization/PopForumsUserAttribute.cs

Did you find a place while debugging that there are multiple instances of the same identity in the collection? That would be pretty weird, because the attribute code should only run once when executing a method. I wonder if "reexecute" runs in the same context, and therefore executes the second action (and therefore attribute) without starting over. If that's the case, then it's probably a tweak to the OnAuthorization method to not add the identity if it's already there.

If you can make that tweak in a PR, I'd be happy to pull it in.

**Comment by ed11s8c** [comment]
@jeffputz Yes, when I run in debug the exception above (image) is exactly what is thrown showing two claimsIdentities on the User's Identity.

I can see that ClaimsIdentities are added on line 87 within the `AuthorizationController.cs` however I see nowhere else they are added to the user, within the solution.

Putting a break point on line 34 on `PopForumsUserAttribute.cs`: 
I visit `/Forums/Setup` the user has a single ClaimIdentity going to the `SetupController.cs`. Allowing that to run, it is hit again this time going to the `HomeController.cs` (my configured reExecute route) and it now has two ClaimIdentity.

**Comment by jeffputz** [comment]
OK, so this actually sounds like a bug in Core, or an unintended consequence of UseStatusCodePagesWithReExecute. The framework is hydrating the identities twice. Let me noodle this a bit and look at the framework code, and see if there is something obvious. While certainly you could just take the first identity, then you have more than one and you can't be sure about which one you're adding roles to.

Of course, this worked fine before Core. :)

**Comment by ed11s8c** [comment]
@jeffputz I will also add, during my debugging I noticed that `app.UseExceptionHandler(...);` also causes the same issue. This seems to be the preferred method of error handling in dotnet core throughout the docs.

Yeah, I agree. Using first is not ideal preferably we can get to the bottom of this and continue to use Single.

**Comment by jeffputz** [comment]
Finally getting a look at this. Interestingly, it breaks the logging too, because it wants to grab the identity of the user that caused the error. It doesn't feel like I'm doing anything that would cause the identities to be populated twice, and of course just the name of "UseStatusCodePagesWithReExecute" implies it's running the same code twice in the same request context. I'll file a bug, then duck and cover.

**Comment by jeffputz** [comment]
The first comment at https://github.com/aspnet/Security/issues/1316 suggests that moving the error page config to late in the middleware chain "fixes" the problem, so I'll suggest that for now instead of changing the PopForumsUserAttribute to check the FirstOrDefault instead of SingleOrDefault. Will close this for now, unless there is alternate guidance from the aspnet security issue.
