### ISSUE TITLE
SQL Setup Script: Warning about Maximum key length for clustered index 

### ISSUE THREAD

**Issue by CryptoJones** [POPWorldMedia/POPForums#58]
When running the initial database script in SSMS, the following warning is received; 
"Warning! The maximum key length for a clustered index is 900 bytes. The index 'PK_pf_ServiceHeartbeat' has maximum length of 1024 bytes. For some combination of large values, the insert/update operation will fail."

**Comment by TheYorkshireDev** [comment]
I have also encountered this issue and mentioned it in #56 

I changed the [database](https://github.com/POPWorldMedia/POPForums/blob/master/src/PopForums.Sql/PopForums.sql#L887) script locally

```
CREATE TABLE [dbo].[pf_ServiceHeartbeat](
	[ServiceName] [nvarchar](193) NOT NULL,
	[MachineName] [nvarchar](256) NOT NULL,
	[LastRun] [datetime] NOT NULL,
 CONSTRAINT [PK_pf_ServiceHeartbeat] PRIMARY KEY CLUSTERED 
(
	[ServiceName] ASC,
	[MachineName] ASC
)
)
```

Note that the `[ServiceName]` column size has been reduced to `193` this makes the total go just under the 900 byte mark. Since we know none of the service names are close to 193 and then allowing for the potential edge case of a machine name 256 bytes long
